sudo: false
language: python
python:
- '3.6'
branches:
  only:
  - build-system
install:
- pip3 install Cython gitlint pybuilder pdoc
#before_script:
#- pip3 install pybuilder pdoc
script:
- gitlint
after_success:
- pdoc --html --html-dir build/docs deeppavlov